---
title: 动态网站的搭建
author: ''
date: '2022-02-14'
slug: site
categories: []
tags: []
---
> huhud
> swswsw

> 你的温暖的我 

<blockquote><p><span>大家好，我是Zero Alan，初次见面，请多多关照。</span></p></blockquote>

因为我的个人网站刚刚搭建完成，完成了基本的网站框架，剩下的就是简单的美化（因为我个人比较喜欢简洁）和输出一些文章。

那第一篇文章就是跟大家聊聊我的一些网站搭建的经验，如果自己在搭建网站的过程中有遇到任何的问题，欢迎大家及时在下方评论提出问题，如果我看到的话，一定会第一时间回复的，一起学习，一起进步。

那在开始之前，我想先说明一下，我的这篇文章是最最初级的，可以说是给一点都不会、一点都没经验的新手看的，并且会比较侧重于搭建前的准备，至于搭建的过程网络上有教学视频，我也会将链接放在文末。

## 确定网站的基本形式

首先你要先决定好你要搭建一个什么样形式的网站，最基本的你要知道自己准备搭建静态网站还是动态网站。静态完整具备访问速度快，可以不需要服务器等优点，但不具备动态网站的登录功能以及动态化管理。动态网站是现在比较流行的网站类型。具体区别大家可自行搜索了解。本网站是动态网站。

## 搭建网站前需要准备的东西

在确定自己所要搭建的网站的类型是动态网站后（以下内容均是针对动态网站的搭建），我们需要知道要搭建网站需要准备哪些东西，即要知道网站的基本原理。当用户提出访问请求访问页面的时候，需要有一个在线的服务器及时处理并从数据库中调出相应的页面并以网页的形式呈现给访问者。这里的服务器和数据库就像是一台24小时在线的计算机，我们需要有这样一台计算机，而这样的计算机我们叫做云主机。

换句话说，我们需要购买云主机或者云服务器，云服务器或云主机可以从阿里云、腾讯云或华为云购买，如果购买国外的云服务器的话，也有几大厂商可以推荐，比如搬瓦工、Bluehost等。可以自行百度了解一下服务器购买的相关推荐。本网站采用的是阿里云的轻量应用服务器。

有了一台云服务器之后，我们还需要有自己的域名，所谓域名就相当于网址，一个好听有好记的网址，比如 baidu.com 或者我的 zeroalan.cc ，网站搭建完成之后，只要访问者输入这些域名，就可以直接打开对应的网站。域名的获取也是需要购买的，毕竟世界上没有免费的午餐，并且我们要知道免费的就是最贵的。购买域名可以上国内的阿里云，也可以去国外的namesilo（也比较便宜），域名的购买是件大事，一定要取个自己满意的名字。

注意：购买云服务器和域名一定要再三斟酌，考虑得慎重一些。

## 关于备案

备案是国内网站必须要做的事情。备案的时间一般是7-20天左右，我在阿里云完成备案，大概一共花了8天时间，其实备案是非常容易的，尤其是阿里云上买的服务器，花几分钟时间填写一下网站信息，然后提交审核，阿里那边会先帮你初审，通过后再提交管局审核，你要做的就是等，等待审核下来。不如就趁这个时间好好学习一下后续网站的搭建。

在搭建自己的网站之前，要想清楚自己的网站是否要备案，如果自己不介意备案的话，就可以放心大胆地买国内服务器。如果自己不想备案的话，那就需要购买国外的服务器或者阿里云的部署在香港等国外地区的服务器，包括域名的购买最好也选择国外的商家。

反正记住一点，如果你购买的是位于国内的服务器，你必须要备案。

## 域名解析

接下来就涉及到技术操作了，我们在准备了建站必备的一些东西之后，开始正式搭建网站了。那不妨我们第一步就是完成一下域名的解析吧，域名的解析步骤可以在你所购买的域名的商家那找到，添加解析记录，解析到你的云服务器的IP地址，这样以后输入你的域名之后就可以跳转其对应的主机，也就是你的云服务器，现在知道域名的作用了吧，主机的名字IP地址这么长多难记。

域名解析的具体做法可以参见视频。

## 安装宝塔面板

前提：在你购买云服务器时，最好选择CentOS系统，包括像我用的轻量应用服务器。

首先我们需要用工具实现和云服务器的连接，Windows系统推荐Xshell软件，打开Xshell软件，输入云服务器IP地址以及对应密码，账号名称一般是root。连接成功后，在命令行输入

```
yum install -y wget && wget -O install.sh http://download.bt.cn/install/install_6.0.sh && sh install.sh
```

该命令是在你的云服务器上安装宝塔面板，等待几分钟，会出现宝塔面板的地址，用户名以及密码，这些信息需要保存好。

## 安装Wordpress

WordPress可以直接在宝塔面板上安装，非常方便易用。安装完成后要注意放行相应端口。

## 完结

到这里网站的搭建就算基本完成了，框架已经有了。接下来需要进行的是SSL证书的配置，强制跳转HTTPS设置的操作，可以参照视频去做。

视频链接来自于[老郭种树](https://guozh.net/)：[https://youtu.be/Y4gQhXgCHiY](https://www.youtube.com/watch?v=Y4gQhXgCHiY&t=0s)









